### PR TITLE
Network input get stuck fix

### PR DESCRIPTION
**Pull request by zabolotiny**
Fix for the issue when network input freezes with some value [https://github.com/Sinclair81/Homebridge-Logo-TS/issues/11](url)

### CODE REVIEW

**Comment by zabolotiny** [comment]
Same PR should fix issue #8 
Fixed as a result of adding retry logic with small delay

**Comment by Sinclair81** [comment]
Ok, that looks pretty good. Have you already tested this in your Homebridge?
At the moment I don't have a 0BA7 logo on the Homebridge and so I can't test it.
I am currently using an 8.FS4 as a bridge (ModBus <-> S7) for my 2 old 0BA7s.

**Comment by zabolotiny** [comment]
@Sinclair81 I am actively using 0BA8 SW.3 and that looks good for me

**Comment by Sinclair81** [comment]
I was able to test it.
HomeBridge-pr1-test
Scenes take a long time but it works!!
If you want you can also take a look at the other error messages and how to fix it!
[Issue # 10](https://github.com/Sinclair81/Homebridge-Logo-TS/issues/10)

Kind regards

**Pull request merged**
